import React, { useMemo, useState } from 'react';
import { BarChart3, TrendingUp, Coins, CheckCircle2, AlertTriangle, Building2 } from 'lucide-react';
import { ReconciliationArchive, User } from '../types';
import { getArchiveData } from '../utils/storage';

interface Props { user: User; }
const money = (n: number) => n.toLocaleString('ru-RU', { maximumFractionDigits: 0 });

export const BankRrnAnalytics: React.FC<Props> = ({ user }) => {
  const [archive] = useState<ReconciliationArchive[]>(getArchiveData());
  const [bank, setBank] = useState('(Все)');
  const [month, setMonth] = useState('(Все)');
  const banks = useMemo(() => Array.from(new Set(archive.map(a => a.bank_name))).sort(), [archive]);
  const months = useMemo(() => Array.from(new Set(archive.map(a => a.period_month || a.timestamp.slice(0,7)))).sort().reverse(), [archive]);
  const filtered = useMemo(() => archive.filter(a => (bank==='(Все)' || a.bank_name===bank) && (month==='(Все)' || (a.period_month || a.timestamp.slice(0,7))===month)), [archive, bank, month]);
  const totals = useMemo(() => filtered.reduce((s,a) => ({ our:s.our+a.total_our, bank:s.bank+a.total_bank, diff:s.diff+a.difference, comm:s.comm+(a.total_commission||0), matched:s.matched+a.matched_count, total:s.total+a.matched_count+a.mismatch_count+a.only_our_count+a.only_bank_count }), {our:0,bank:0,diff:0,comm:0,matched:0,total:0}), [filtered]);
  const rate = totals.total ? totals.matched/totals.total*100 : 0;
  const terminalRows = useMemo(() => { const map = new Map<string,{tid:string; bank:string; tx:number; volume:number; commission:number; net:number}>(); filtered.forEach(a => (a.terminals_summary||[]).forEach(t => { const x=map.get(t.terminal_id)||{tid:t.terminal_id,bank:t.bank_acquirer||a.bank_name,tx:0,volume:0,commission:0,net:0}; x.tx+=t.tx_count; x.volume+=t.total_volume; x.commission+=t.commission_amount; x.net+=t.net_volume; map.set(t.terminal_id,x); })); return Array.from(map.values()).sort((a,b)=>b.volume-a.volume).slice(0,8); }, [filtered]);

  return <div className="space-y-5">
    <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4"><div><h3 className="text-xl font-bold text-slate-900 flex items-center gap-2"><BarChart3 className="w-5 h-5 text-indigo-600" /> Аналитика Bank RRN</h3><p className="text-sm text-slate-500 mt-1">Глубокий анализ объёма, качества сопоставления, комиссий и терминалов.</p></div><div className="flex gap-2"><select value={bank} onChange={e=>setBank(e.target.value)} className="px-3 py-2.5 rounded-lg border border-slate-200 bg-white text-sm"><option>(Все)</option>{banks.map(b=><option key={b}>{b}</option>)}</select><select value={month} onChange={e=>setMonth(e.target.value)} className="px-3 py-2.5 rounded-lg border border-slate-200 bg-white text-sm"><option>(Все)</option>{months.map(m=><option key={m}>{m}</option>)}</select></div></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">{[{l:'Match rate',v:`${rate.toFixed(1)}%`,i:CheckCircle2,c:'text-emerald-600 bg-emerald-50'},{l:'Оборот',v:money(totals.bank),i:TrendingUp,c:'text-indigo-600 bg-indigo-50'},{l:'Комиссия',v:money(totals.comm),i:Coins,c:'text-violet-600 bg-violet-50'},{l:'Δ суммы',v:money(totals.diff),i:AlertTriangle,c:totals.diff===0?'text-emerald-600 bg-emerald-50':'text-amber-600 bg-amber-50'}].map(x=>{const I=x.i;return <div key={x.l} className="bg-white border border-slate-200 rounded-xl p-4 shadow-xs"><div className="flex justify-between"><div><div className="text-xs text-slate-500">{x.l}</div><div className="text-xl font-bold mt-1 text-slate-900">{x.v}</div></div><div className={`w-9 h-9 rounded-lg flex items-center justify-center ${x.c}`}><I className="w-4 h-4"/></div></div></div>})}</div>
    <div className="grid grid-cols-1 xl:grid-cols-2 gap-5"><div className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs"><div className="flex items-center justify-between mb-4"><div><h4 className="font-semibold text-slate-900">Динамика по запускам</h4><p className="text-xs text-slate-500">Объём и качество последних результатов</p></div><Building2 className="w-5 h-5 text-slate-300"/></div><div className="space-y-3">{filtered.slice(0,8).map(a=>{const c=a.matched_count+a.mismatch_count+a.only_our_count+a.only_bank_count;const r=c?a.matched_count/c*100:0;return <div key={a.id}><div className="flex justify-between text-xs mb-1"><span className="text-slate-600">{new Date(a.timestamp).toLocaleDateString('ru-RU')} · {a.bank_name}</span><span className="font-semibold">{r.toFixed(1)}%</span></div><div className="h-2 rounded-full bg-slate-100 overflow-hidden"><div className="h-full bg-indigo-500 rounded-full" style={{width:`${Math.min(100,r)}%`}}/></div></div>})}</div></div><div className="bg-slate-900 text-white rounded-xl p-5 shadow-xs"><div className="text-xs font-semibold text-indigo-200 uppercase tracking-wider">Период анализа</div><div className="text-3xl font-bold mt-2">{filtered.length}</div><div className="text-sm text-slate-300 mt-1">сохранённых запусков</div><div className="grid grid-cols-2 gap-3 mt-6"><div className="bg-white/5 rounded-xl p-3"><div className="text-[11px] text-slate-400">Наш реестр</div><div className="font-semibold mt-1">{money(totals.our)}</div></div><div className="bg-white/5 rounded-xl p-3"><div className="text-[11px] text-slate-400">Банк</div><div className="font-semibold mt-1">{money(totals.bank)}</div></div></div><div className="mt-4 text-xs text-slate-400">Пользователь: {user.username}</div></div></div>
    <div className="bg-white border border-slate-200 rounded-xl shadow-xs overflow-hidden"><div className="px-5 py-4 border-b border-slate-100"><h4 className="font-semibold text-slate-900">Топ терминалов по обороту</h4><p className="text-xs text-slate-500 mt-0.5">Агрегация по выбранным фильтрам</p></div>{terminalRows.length===0?<div className="p-10 text-center text-sm text-slate-500">Нет терминальной детализации.</div>:<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50"><tr>{['TID','Банк','Транзакции','Оборот','Комиссия','Нетто'].map(h=><th key={h} className="px-5 py-3 text-left text-[11px] font-semibold uppercase tracking-wider text-slate-400">{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{terminalRows.map(t=><tr key={t.tid} className="hover:bg-slate-50"><td className="px-5 py-3.5 font-mono">{t.tid}</td><td className="px-5 py-3.5">{t.bank}</td><td className="px-5 py-3.5">{t.tx.toLocaleString('ru-RU')}</td><td className="px-5 py-3.5 font-semibold">{money(t.volume)}</td><td className="px-5 py-3.5 text-slate-600">{money(t.commission)}</td><td className="px-5 py-3.5 font-semibold">{money(t.net)}</td></tr>)}</tbody></table></div>}</div>
  </div>;
};
